name: PHPStan

on:
  push:

jobs:
  tests:
    name: Analyse
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
        env:
          fail-fast: true

      - name: Install dependencies
        run: composer install

      - name: Analyse
        run: vendor/bin/phpstan
